version: 2
updates:
   - package-ecosystem: "npm"
     directory: /
     schedule:
        interval: "daily"
   #   allow:
   #      - dependency-name: "math-lib"
   #      - dependency-name: "express"
   #      - dependency-name: "webix"
